"""
silmaril.universe.sp500_fill — completes the S&P 500 (ALPHA 1.0 request).

The original expanded.SP500 list was "trimmed but representative" (~254
equities reached the universe). This module adds the REMAINING constituents
so the tracked universe covers the full index. Purely additive: merged via
build_expanded_universe's existing dedup, so any overlap with hand-curated
lists is harmless and the curated entries win (first-seen order).

HONESTY NOTE: this is a static, best-effort membership list (sector-tagged
GICS, knowledge as of early 2026) — the sandbox that authored it has no
market egress to pull the official roster. A ticker that has since been
removed/merged simply returns no prices and gets no debates (harmless).
Verify against the official constituents on the next networked pass and
prune via attic, never delete. Index membership churns ~5%/yr; a quarterly
glance is plenty.

Each entry: (ticker, display_name, GICS-style sector tag matching the
sector vocabulary already used in expanded.py).
"""

from __future__ import annotations
from typing import List, Tuple

SP500_FILL: List[Tuple[str, str, str]] = [
    # ── Technology ──────────────────────────────────────────────
    ("ACN", "Accenture", "Technology"),
    ("IBM", "IBM", "Technology"),
    ("NOW", "ServiceNow", "Technology"),
    ("INTU", "Intuit", "Technology"),
    ("AMAT", "Applied Materials", "Technology"),
    ("ADI", "Analog Devices", "Technology"),
    ("MU", "Micron Technology", "Technology"),
    ("PANW", "Palo Alto Networks", "Technology"),
    ("SNPS", "Synopsys", "Technology"),
    ("CDNS", "Cadence Design Systems", "Technology"),
    ("CRWD", "CrowdStrike", "Technology"),
    ("ROP", "Roper Technologies", "Technology"),
    ("ADSK", "Autodesk", "Technology"),
    ("FTNT", "Fortinet", "Technology"),
    ("NXPI", "NXP Semiconductors", "Technology"),
    ("MCHP", "Microchip Technology", "Technology"),
    ("MPWR", "Monolithic Power Systems", "Technology"),
    ("MSI", "Motorola Solutions", "Technology"),
    ("GLW", "Corning", "Technology"),
    ("APH", "Amphenol", "Technology"),
    ("TEL", "TE Connectivity", "Technology"),
    ("HPQ", "HP Inc.", "Technology"),
    ("HPE", "Hewlett Packard Enterprise", "Technology"),
    ("DELL", "Dell Technologies", "Technology"),
    ("NTAP", "NetApp", "Technology"),
    ("WDC", "Western Digital", "Technology"),
    ("STX", "Seagate Technology", "Technology"),
    ("KEYS", "Keysight Technologies", "Technology"),
    ("TDY", "Teledyne Technologies", "Technology"),
    ("TRMB", "Trimble", "Technology"),
    ("ZBRA", "Zebra Technologies", "Technology"),
    ("AKAM", "Akamai Technologies", "Technology"),
    ("FFIV", "F5", "Technology"),
    ("JNPR", "Juniper Networks", "Technology"),
    ("GEN", "Gen Digital", "Technology"),
    ("EPAM", "EPAM Systems", "Technology"),
    ("CDW", "CDW", "Technology"),
    ("IT", "Gartner", "Technology"),
    ("CTSH", "Cognizant", "Technology"),
    ("GDDY", "GoDaddy", "Technology"),
    ("TYL", "Tyler Technologies", "Technology"),
    ("PTC", "PTC", "Technology"),
    ("ANSS", "Ansys", "Technology"),
    ("ON", "ON Semiconductor", "Technology"),
    ("SWKS", "Skyworks Solutions", "Technology"),
    ("QRVO", "Qorvo", "Technology"),
    ("FSLR", "First Solar", "Technology"),
    ("ENPH", "Enphase Energy", "Technology"),
    ("SMCI", "Super Micro Computer", "Technology"),
    ("PLTR", "Palantir Technologies", "Technology"),
    ("VRSN", "VeriSign", "Technology"),
    ("FICO", "Fair Isaac", "Technology"),
    ("JBL", "Jabil", "Technology"),
    # ── Financials ──────────────────────────────────────────────
    ("BRK-B", "Berkshire Hathaway B", "Financials"),
    ("SPGI", "S&P Global", "Financials"),
    ("PGR", "Progressive", "Financials"),
    ("CB", "Chubb", "Financials"),
    ("MMC", "Marsh & McLennan", "Financials"),
    ("ICE", "Intercontinental Exchange", "Financials"),
    ("CME", "CME Group", "Financials"),
    ("MCO", "Moody's", "Financials"),
    ("AON", "Aon", "Financials"),
    ("PNC", "PNC Financial Services", "Financials"),
    ("USB", "U.S. Bancorp", "Financials"),
    ("TFC", "Truist Financial", "Financials"),
    ("AIG", "American International Group", "Financials"),
    ("MET", "MetLife", "Financials"),
    ("PRU", "Prudential Financial", "Financials"),
    ("AFL", "Aflac", "Financials"),
    ("ALL", "Allstate", "Financials"),
    ("TRV", "Travelers", "Financials"),
    ("AJG", "Arthur J. Gallagher", "Financials"),
    ("MSCI", "MSCI", "Financials"),
    ("NDAQ", "Nasdaq", "Financials"),
    ("CBOE", "Cboe Global Markets", "Financials"),
    ("BK", "BNY Mellon", "Financials"),
    ("STT", "State Street", "Financials"),
    ("NTRS", "Northern Trust", "Financials"),
    ("FITB", "Fifth Third Bancorp", "Financials"),
    ("HBAN", "Huntington Bancshares", "Financials"),
    ("RF", "Regions Financial", "Financials"),
    ("CFG", "Citizens Financial Group", "Financials"),
    ("KEY", "KeyCorp", "Financials"),
    ("MTB", "M&T Bank", "Financials"),
    ("SYF", "Synchrony Financial", "Financials"),
    ("DFS", "Discover Financial Services", "Financials"),
    ("COF", "Capital One", "Financials"),
    ("FIS", "Fidelity National Information", "Financials"),
    ("FI", "Fiserv", "Financials"),
    ("GPN", "Global Payments", "Financials"),
    ("WTW", "Willis Towers Watson", "Financials"),
    ("HIG", "Hartford Financial", "Financials"),
    ("CINF", "Cincinnati Financial", "Financials"),
    ("L", "Loews", "Financials"),
    ("GL", "Globe Life", "Financials"),
    ("AIZ", "Assurant", "Financials"),
    ("BRO", "Brown & Brown", "Financials"),
    ("WRB", "W. R. Berkley", "Financials"),
    ("EG", "Everest Group", "Financials"),
    ("ACGL", "Arch Capital Group", "Financials"),
    ("FDS", "FactSet Research", "Financials"),
    ("MKTX", "MarketAxess", "Financials"),
    ("IVZ", "Invesco", "Financials"),
    ("TROW", "T. Rowe Price", "Financials"),
    ("BEN", "Franklin Resources", "Financials"),
    ("AMP", "Ameriprise Financial", "Financials"),
    ("RJF", "Raymond James Financial", "Financials"),
    # ── Healthcare ──────────────────────────────────────────────
    ("LLY", "Eli Lilly", "Healthcare"),
    ("ISRG", "Intuitive Surgical", "Healthcare"),
    ("SYK", "Stryker", "Healthcare"),
    ("BSX", "Boston Scientific", "Healthcare"),
    ("MDT", "Medtronic", "Healthcare"),
    ("CI", "Cigna", "Healthcare"),
    ("ELV", "Elevance Health", "Healthcare"),
    ("HUM", "Humana", "Healthcare"),
    ("CNC", "Centene", "Healthcare"),
    ("MCK", "McKesson", "Healthcare"),
    ("COR", "Cencora", "Healthcare"),
    ("CAH", "Cardinal Health", "Healthcare"),
    ("ZTS", "Zoetis", "Healthcare"),
    ("BDX", "Becton Dickinson", "Healthcare"),
    ("EW", "Edwards Lifesciences", "Healthcare"),
    ("RMD", "ResMed", "Healthcare"),
    ("IDXX", "IDEXX Laboratories", "Healthcare"),
    ("A", "Agilent Technologies", "Healthcare"),
    ("IQV", "IQVIA Holdings", "Healthcare"),
    ("MTD", "Mettler-Toledo", "Healthcare"),
    ("WAT", "Waters", "Healthcare"),
    ("STE", "Steris", "Healthcare"),
    ("HOLX", "Hologic", "Healthcare"),
    ("BAX", "Baxter International", "Healthcare"),
    ("ZBH", "Zimmer Biomet", "Healthcare"),
    ("COO", "Cooper Companies", "Healthcare"),
    ("ALGN", "Align Technology", "Healthcare"),
    ("DXCM", "DexCom", "Healthcare"),
    ("PODD", "Insulet", "Healthcare"),
    ("BIIB", "Biogen", "Healthcare"),
    ("INCY", "Incyte", "Healthcare"),
    ("MRNA", "Moderna", "Healthcare"),
    ("VTRS", "Viatris", "Healthcare"),
    ("DGX", "Quest Diagnostics", "Healthcare"),
    ("LH", "Labcorp", "Healthcare"),
    ("HCA", "HCA Healthcare", "Healthcare"),
    ("UHS", "Universal Health Services", "Healthcare"),
    ("MOH", "Molina Healthcare", "Healthcare"),
    ("CRL", "Charles River Laboratories", "Healthcare"),
    ("TECH", "Bio-Techne", "Healthcare"),
    ("RVTY", "Revvity", "Healthcare"),
    ("SOLV", "Solventum", "Healthcare"),
    ("GEHC", "GE HealthCare", "Healthcare"),
    # ── Discretionary ───────────────────────────────────────────
    ("BKNG", "Booking Holdings", "Discretionary"),
    ("TJX", "TJX Companies", "Discretionary"),
    ("ORLY", "O'Reilly Automotive", "Discretionary"),
    ("AZO", "AutoZone", "Discretionary"),
    ("ROST", "Ross Stores", "Discretionary"),
    ("YUM", "Yum! Brands", "Discretionary"),
    ("DRI", "Darden Restaurants", "Discretionary"),
    ("MAR", "Marriott International", "Discretionary"),
    ("HLT", "Hilton Worldwide", "Discretionary"),
    ("RCL", "Royal Caribbean", "Discretionary"),
    ("CCL", "Carnival", "Discretionary"),
    ("NCLH", "Norwegian Cruise Line", "Discretionary"),
    ("EXPE", "Expedia Group", "Discretionary"),
    ("ABNB", "Airbnb", "Discretionary"),
    ("LVS", "Las Vegas Sands", "Discretionary"),
    ("WYNN", "Wynn Resorts", "Discretionary"),
    ("MGM", "MGM Resorts", "Discretionary"),
    ("CZR", "Caesars Entertainment", "Discretionary"),
    ("DPZ", "Domino's Pizza", "Discretionary"),
    ("CMG", "Chipotle Mexican Grill", "Discretionary"),
    ("ULTA", "Ulta Beauty", "Discretionary"),
    ("BBY", "Best Buy", "Discretionary"),
    ("DG", "Dollar General", "Discretionary"),
    ("DLTR", "Dollar Tree", "Discretionary"),
    ("KMX", "CarMax", "Discretionary"),
    ("APTV", "Aptiv", "Discretionary"),
    ("BWA", "BorgWarner", "Discretionary"),
    ("LKQ", "LKQ", "Discretionary"),
    ("GRMN", "Garmin", "Discretionary"),
    ("POOL", "Pool Corporation", "Discretionary"),
    ("TSCO", "Tractor Supply", "Discretionary"),
    ("DECK", "Deckers Outdoor", "Discretionary"),
    ("LULU", "Lululemon Athletica", "Discretionary"),
    ("RL", "Ralph Lauren", "Discretionary"),
    ("TPR", "Tapestry", "Discretionary"),
    ("PHM", "PulteGroup", "Discretionary"),
    ("DHI", "D.R. Horton", "Discretionary"),
    ("LEN", "Lennar", "Discretionary"),
    ("NVR", "NVR", "Discretionary"),
    ("GPC", "Genuine Parts", "Discretionary"),
    ("EBAY", "eBay", "Discretionary"),
    ("MHK", "Mohawk Industries", "Discretionary"),
    ("WSM", "Williams-Sonoma", "Discretionary"),
    # ── Staples ─────────────────────────────────────────────────
    ("MDLZ", "Mondelez International", "Staples"),
    ("CL", "Colgate-Palmolive", "Staples"),
    ("KMB", "Kimberly-Clark", "Staples"),
    ("GIS", "General Mills", "Staples"),
    ("KHC", "Kraft Heinz", "Staples"),
    ("HSY", "Hershey", "Staples"),
    ("K", "Kellanova", "Staples"),
    ("SYY", "Sysco", "Staples"),
    ("STZ", "Constellation Brands", "Staples"),
    ("BF-B", "Brown-Forman B", "Staples"),
    ("TAP", "Molson Coors", "Staples"),
    ("CHD", "Church & Dwight", "Staples"),
    ("CLX", "Clorox", "Staples"),
    ("EL", "Estee Lauder", "Staples"),
    ("KVUE", "Kenvue", "Staples"),
    ("TSN", "Tyson Foods", "Staples"),
    ("HRL", "Hormel Foods", "Staples"),
    ("CAG", "Conagra Brands", "Staples"),
    ("CPB", "Campbell's", "Staples"),
    ("SJM", "J.M. Smucker", "Staples"),
    ("MKC", "McCormick", "Staples"),
    ("LW", "Lamb Weston", "Staples"),
    ("BG", "Bunge Global", "Staples"),
    ("ADM", "Archer-Daniels-Midland", "Staples"),
    ("KR", "Kroger", "Staples"),
    ("DGX", "Quest Diagnostics", "Healthcare"),
    # ── Industrials ─────────────────────────────────────────────
    ("GE", "GE Aerospace", "Industrials"),
    ("RTX", "RTX", "Industrials"),
    ("ETN", "Eaton", "Industrials"),
    ("PH", "Parker-Hannifin", "Industrials"),
    ("ITW", "Illinois Tool Works", "Industrials"),
    ("EMR", "Emerson Electric", "Industrials"),
    ("CMI", "Cummins", "Industrials"),
    ("PCAR", "PACCAR", "Industrials"),
    ("CSX", "CSX", "Industrials"),
    ("NSC", "Norfolk Southern", "Industrials"),
    ("ODFL", "Old Dominion Freight Line", "Industrials"),
    ("JBHT", "J.B. Hunt Transport", "Industrials"),
    ("CHRW", "C.H. Robinson", "Industrials"),
    ("EXPD", "Expeditors International", "Industrials"),
    ("WM", "Waste Management", "Industrials"),
    ("RSG", "Republic Services", "Industrials"),
    ("CTAS", "Cintas", "Industrials"),
    ("FAST", "Fastenal", "Industrials"),
    ("GWW", "W.W. Grainger", "Industrials"),
    ("AME", "AMETEK", "Industrials"),
    ("ROK", "Rockwell Automation", "Industrials"),
    ("DOV", "Dover", "Industrials"),
    ("XYL", "Xylem", "Industrials"),
    ("IEX", "IDEX", "Industrials"),
    ("FTV", "Fortive", "Industrials"),
    ("HUBB", "Hubbell", "Industrials"),
    ("LDOS", "Leidos Holdings", "Industrials"),
    ("LHX", "L3Harris Technologies", "Industrials"),
    ("HWM", "Howmet Aerospace", "Industrials"),
    ("TXT", "Textron", "Industrials"),
    ("HII", "Huntington Ingalls", "Industrials"),
    ("AXON", "Axon Enterprise", "Industrials"),
    ("URI", "United Rentals", "Industrials"),
    ("PWR", "Quanta Services", "Industrials"),
    ("EME", "EMCOR Group", "Industrials"),
    ("J", "Jacobs Solutions", "Industrials"),
    ("SNA", "Snap-on", "Industrials"),
    ("SWK", "Stanley Black & Decker", "Industrials"),
    ("MAS", "Masco", "Industrials"),
    ("AOS", "A. O. Smith", "Industrials"),
    ("ALLE", "Allegion", "Industrials"),
    ("JCI", "Johnson Controls", "Industrials"),
    ("CARR", "Carrier Global", "Industrials"),
    ("TT", "Trane Technologies", "Industrials"),
    ("OTIS", "Otis Worldwide", "Industrials"),
    ("IR", "Ingersoll Rand", "Industrials"),
    ("GNRC", "Generac Holdings", "Industrials"),
    ("NDSN", "Nordson", "Industrials"),
    ("PNR", "Pentair", "Industrials"),
    ("DAY", "Dayforce", "Industrials"),
    ("PAYX", "Paychex", "Industrials"),
    ("ADP", "Automatic Data Processing", "Industrials"),
    ("BR", "Broadridge Financial", "Industrials"),
    ("VRSK", "Verisk Analytics", "Industrials"),
    ("EFX", "Equifax", "Industrials"),
    ("UBER", "Uber Technologies", "Industrials"),
    ("DAL", "Delta Air Lines", "Industrials"),
    ("UAL", "United Airlines", "Industrials"),
    ("LUV", "Southwest Airlines", "Industrials"),
    ("AAL", "American Airlines", "Industrials"),
    # ── Energy ──────────────────────────────────────────────────
    ("EOG", "EOG Resources", "Energy"),
    ("PSX", "Phillips 66", "Energy"),
    ("MPC", "Marathon Petroleum", "Energy"),
    ("VLO", "Valero Energy", "Energy"),
    ("OKE", "ONEOK", "Energy"),
    ("WMB", "Williams Companies", "Energy"),
    ("KMI", "Kinder Morgan", "Energy"),
    ("TRGP", "Targa Resources", "Energy"),
    ("FANG", "Diamondback Energy", "Energy"),
    ("DVN", "Devon Energy", "Energy"),
    ("CTRA", "Coterra Energy", "Energy"),
    ("EQT", "EQT", "Energy"),
    ("APA", "APA", "Energy"),
    ("BKR", "Baker Hughes", "Energy"),
    ("HAL", "Halliburton", "Energy"),
    ("TPL", "Texas Pacific Land", "Energy"),
    # ── Materials ───────────────────────────────────────────────
    ("LIN", "Linde", "Materials"),
    ("APD", "Air Products and Chemicals", "Materials"),
    ("SHW", "Sherwin-Williams", "Materials"),
    ("ECL", "Ecolab", "Materials"),
    ("FCX", "Freeport-McMoRan", "Materials"),
    ("NEM", "Newmont", "Materials"),
    ("NUE", "Nucor", "Materials"),
    ("STLD", "Steel Dynamics", "Materials"),
    ("DOW", "Dow", "Materials"),
    ("LYB", "LyondellBasell", "Materials"),
    ("DD", "DuPont de Nemours", "Materials"),
    ("PPG", "PPG Industries", "Materials"),
    ("IP", "International Paper", "Materials"),
    ("PKG", "Packaging Corp of America", "Materials"),
    ("AMCR", "Amcor", "Materials"),
    ("BALL", "Ball", "Materials"),
    ("AVY", "Avery Dennison", "Materials"),
    ("CF", "CF Industries", "Materials"),
    ("MOS", "Mosaic", "Materials"),
    ("ALB", "Albemarle", "Materials"),
    ("IFF", "International Flavors & Fragrances", "Materials"),
    ("CE", "Celanese", "Materials"),
    ("EMN", "Eastman Chemical", "Materials"),
    ("MLM", "Martin Marietta Materials", "Materials"),
    ("VMC", "Vulcan Materials", "Materials"),
    ("SMR", "NuScale Power", "Materials"),
    # ── Utilities ───────────────────────────────────────────────
    ("SO", "Southern Company", "Utilities"),
    ("DUK", "Duke Energy", "Utilities"),
    ("CEG", "Constellation Energy", "Utilities"),
    ("SRE", "Sempra", "Utilities"),
    ("AEP", "American Electric Power", "Utilities"),
    ("D", "Dominion Energy", "Utilities"),
    ("PCG", "PG&E", "Utilities"),
    ("EXC", "Exelon", "Utilities"),
    ("XEL", "Xcel Energy", "Utilities"),
    ("ED", "Consolidated Edison", "Utilities"),
    ("PEG", "Public Service Enterprise", "Utilities"),
    ("WEC", "WEC Energy Group", "Utilities"),
    ("DTE", "DTE Energy", "Utilities"),
    ("AEE", "Ameren", "Utilities"),
    ("ETR", "Entergy", "Utilities"),
    ("FE", "FirstEnergy", "Utilities"),
    ("PPL", "PPL", "Utilities"),
    ("CMS", "CMS Energy", "Utilities"),
    ("CNP", "CenterPoint Energy", "Utilities"),
    ("NI", "NiSource", "Utilities"),
    ("LNT", "Alliant Energy", "Utilities"),
    ("EVRG", "Evergy", "Utilities"),
    ("ATO", "Atmos Energy", "Utilities"),
    ("ES", "Eversource Energy", "Utilities"),
    ("AWK", "American Water Works", "Utilities"),
    ("VST", "Vistra", "Utilities"),
    ("NRG", "NRG Energy", "Utilities"),
    # ── Real Estate ─────────────────────────────────────────────
    ("PLD", "Prologis", "Real Estate"),
    ("AMT", "American Tower", "Real Estate"),
    ("EQIX", "Equinix", "Real Estate"),
    ("WELL", "Welltower", "Real Estate"),
    ("DLR", "Digital Realty Trust", "Real Estate"),
    ("SPG", "Simon Property Group", "Real Estate"),
    ("PSA", "Public Storage", "Real Estate"),
    ("O", "Realty Income", "Real Estate"),
    ("CCI", "Crown Castle", "Real Estate"),
    ("CBRE", "CBRE Group", "Real Estate"),
    ("VICI", "VICI Properties", "Real Estate"),
    ("EXR", "Extra Space Storage", "Real Estate"),
    ("AVB", "AvalonBay Communities", "Real Estate"),
    ("EQR", "Equity Residential", "Real Estate"),
    ("ESS", "Essex Property Trust", "Real Estate"),
    ("MAA", "Mid-America Apartment", "Real Estate"),
    ("UDR", "UDR", "Real Estate"),
    ("CPT", "Camden Property Trust", "Real Estate"),
    ("IRM", "Iron Mountain", "Real Estate"),
    ("SBAC", "SBA Communications", "Real Estate"),
    ("ARE", "Alexandria Real Estate", "Real Estate"),
    ("BXP", "BXP", "Real Estate"),
    ("VTR", "Ventas", "Real Estate"),
    ("DOC", "Healthpeak Properties", "Real Estate"),
    ("KIM", "Kimco Realty", "Real Estate"),
    ("REG", "Regency Centers", "Real Estate"),
    ("FRT", "Federal Realty", "Real Estate"),
    ("HST", "Host Hotels & Resorts", "Real Estate"),
    ("INVH", "Invitation Homes", "Real Estate"),
    ("AMH", "American Homes 4 Rent", "Real Estate"),
    ("CSGP", "CoStar Group", "Real Estate"),
    # ── Communication ───────────────────────────────────────────
    ("TMUS", "T-Mobile US", "Communication"),
    ("CHTR", "Charter Communications", "Communication"),
    ("EA", "Electronic Arts", "Communication"),
    ("TTWO", "Take-Two Interactive", "Communication"),
    ("WBD", "Warner Bros. Discovery", "Communication"),
    ("FOXA", "Fox Class A", "Communication"),
    ("FOX", "Fox Class B", "Communication"),
    ("NWSA", "News Corp Class A", "Communication"),
    ("NWS", "News Corp Class B", "Communication"),
    ("OMC", "Omnicom Group", "Communication"),
    ("IPG", "Interpublic Group", "Communication"),
    ("MTCH", "Match Group", "Communication"),
    ("LYV", "Live Nation Entertainment", "Communication"),
    ("PARA", "Paramount", "Communication"),
]


def fill_entries() -> List[Tuple[str, str, str]]:
    """Deduped-by-ticker view of the fill list (defensive against
    accidental duplicates inside this file itself)."""
    seen = set()
    out = []
    for tk, name, sector in SP500_FILL:
        if tk in seen:
            continue
        seen.add(tk)
        out.append((tk, name, sector))
    return out
